sudo: required
services:
  - docker

before_install:
  - docker build -t alex030365/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run alex030365/react-test npm run test -- --coverage

after_success:
  - docker build -t alex030365/multi-client ./client
  - docker build -t alex030365/multi-nginx ./nginx
  - docker build -t alex030365/multi-server ./server
  - docker build -t alex030365/multi-worker ./worker
# log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images and push them to docker hub
  - docker push alex030365/multi-client
  - docker push alex030365/multi-nginx
  - docker push alex030365/multi-server
  - docker push alex030365/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-359810349909
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
