# specify base imnage
FROM nginx

# add working directory in docker FS'
# WORKDIR '/app'

# copy Nginx configuration (specify dest file name to guarantee overwrite existed)
COPY ./default.conf /etc/nginx/conf.d/default.conf

